server:
  port: 8080
spring:
  application:
    name: documentKeyAPI
  datasource:
    url: 'jdbc:h2:file:/data/demo'
    username: sa
  jpa:
    show-sql: true
    database-platform: 'org.hibernate.dialect.H2Dialect'
app:
  validador:
    chave: "\\d{44}"
    total-lista-chaves: 20
    total-chaves-validacao: 20
