server:
  port: 8080
spring:
  application:
    name: documentKeyAPI
  datasource:
    url: 'jdbc:h2:file:/data/demo'
    username: sa
  jpa:
    show-sql: true
    database-platform: 'org.hibernate.dialect.H2Dialect'
app:
  validador:
    chave: "\\d{44}"
    formato-linha: "\\d+;\\d{44}"
    total-lista-chaves: 20
    total-chaves-validacao: 20
  batch:
    caminho-diretorio: ${APP-CAMINHO-DIRETORIO}
    habilitar-processo: true
    tempo-execucao-job-milisegundos: 10000
    total-arquivos-por-processo: 100
    total-linhas-por-processo: 1000
    extensoes-arquivo:
      - txt
      - csv
